# CODE TO AGGREGATE 
# merging non-attainment areas with census tracts
# NOTE: all of the files have different projections...
# from EPA website greenbook: https://www.epa.gov/green-book/green-book-gis-download

# Set working directory
#mywd <- "/Users/lingjin/Box/FHWA/Task1"
mywd <- "C:/FHWA/For FHWA folks/microtype_input_preparation"
setwd(mywd)

datadir <- "RawData"
cleandir <- "CleanData"

# Load packages
library(sf)
library(dplyr)
library(data.table)

#########
# LOAD data
############
# importing census tracts boundaries 
# Note June 2022: could re-do this merge with the 2020 census tracts or using the 500K resolution tigerline shapefiles
# instead of the ACS data I used from 2019

# Ling Jin 8/5/2022 added: 
# Note that Natalie's data folder showed individual state data and she combined it in external software to generate the combined tracts.
# but the tracts geometry can be regenerated by following code if needed
# library(tidycensus)
# census_api_key("2e9a585abf38b5ee3cb67040b334942f82ec38e1")
# states = c('AL','AK','AZ','AR','CA','CO','CT','DE',
#            'FL','GA','HI','ID','IL','IN','IA','KS',
#            'KY','LA','ME','MD','MA','MI','MN','MS',
#            'MO','MT','NE','NV','NH','NJ','NM','NY',
#            'NC','ND','OH','OK','OR','PA','RI','SC',
#            'SD','TN','TX','UT','VT','VA','WA','WV',
#            'WI','WY','AS','GU','MP','PR','VI')
# tract_geo = get_decennial(geography = 'tract', year = 2010,
#                           state = states, geometry = TRUE,
#                           variables = c('P001001'))
# tracts = tract_geo[,c('GEOID','geometry')]

tracts <- st_read(file.path(datadir, "Tract_Boundaries/combined_tracts"), 
        query =  "SELECT NAME, GEOID FROM combined_tracts") %>%
  st_as_sf()

# LEAD
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/lead_2008std_naa_shapefile.zip
d = st_read(file.path(datadir, "EPA/air_quality/lead_2008std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
pb2008 = st_intersection(d, tracts) %>%
  mutate(pb2008 = 1) %>%
  select(GEOID, pb2008) # create indicator for lead for each tract

# OZONE 2008
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/ozone_8hr_2008std_naa_shapefile.zip 
e <- st_read(file.path(datadir,"EPA/air_quality/ozone_8hr_2008std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
ozone2008 = st_intersection(d, tracts) %>%
  mutate(ozone2008=1) %>%
  select(GEOID, ozone2008)

#OZONE 2015
# Source link: https://www3.epa.gov/airquality/greenbook/shapefile/ozone_8hr_2015std_naa_shapefile.zip
# Note June 2022: this source link was updated in Feb 2022, I can't find the link for the original dataset I downloaded
d <- st_read(file.path(datadir,"EPA/air_quality/ozone_8hr_2015std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
ozone2015 = st_intersection(d, tracts) %>%
  mutate(ozone2015=1) %>%
  select(GEOID, ozone2015)

# PM 2.5 1997
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/pm25_1997std_naa_shapefile.zip
d <- st_read(file.path(datadir,"EPA/air_quality/pm25_1997std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
pm1997 = st_intersection(d, tracts) %>%
  mutate(pm1997 = 1) %>%
  select(GEOID, pm1997)

# PM 2.5 2006
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/pm25_2006std_naa_shapefile.zip
d <- st_read(file.path(datadir,"EPA/air_quality/pm25_2006std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
pm2006 = st_intersection(d, tracts) %>%
  mutate(pm2006 = 1) %>%
  select(GEOID, pm2006)

# PM 2.5 2012
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/pm25_2012std_naa_shapefile.zip
d <- st_read(file.path(datadir,"EPA/air_quality/pm25_2012std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
pm2012 = st_intersection(d, tracts) %>%
  mutate(pm2012 = 1) %>%
  select(GEOID, pm2012)

#SO2 - 2010
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/so2_2010std_naa_shapefile.zip 
# Note June 2022: this source link was updated in June 2021, I can't find the link for the original dataset I downloaded
d <- st_read(file.path(datadir,"EPA/air_quality/so2_2010std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
so2 = st_intersection(d, tracts) %>%
  mutate(so2 = 1) %>%
  select(GEOID, so2)

# PM 10 -1987
sf_use_s2(FALSE)
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/pm10_1987std_naa_shapefile.zip
d <- st_read(file.path(datadir,"EPA/air_quality/pm10_1987std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
pm10 = st_intersection(d, tracts) %>%
  mutate(pm10 = 1) %>%
  select(GEOID, pm10)

# CO
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/co_1971std_naa_shapefile.zip
d <- st_read(file.path(datadir,"EPA/air_quality/co_1971std_naa_shapefile"))
d <- sf::st_buffer(d, dist = 0)
tracts <- st_transform(tracts , st_crs(d))
co = st_intersection(d, tracts) %>%
  mutate(co = 1) %>%
  select(GEOID, co)

# NO2 
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/no2_1971std_naa_shapefile.zip
d <- st_read(file.path(datadir,"EPA/air_quality/no2_1971std_naa_shapefile"))
d <- sf::st_buffer(d, dist = 0)
tracts <- st_transform(tracts , st_crs(d))
no2 = st_intersection(d, tracts) %>%
  mutate(no2 =1) %>%
  select(GEOID, no2)

# SO2 - 1971
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/so2_1971std_naa_shapefile.zip
d <- st_read(file.path(datadir,"EPA/air_quality/so2_1971std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
so21971 = st_intersection(d, tracts) %>%
  mutate(so2_71 = 1) %>%
  select(GEOID, so2_71)

# LEAD 1978
# source link: https://www3.epa.gov/airquality/greenbook/shapefile/lead_1978std_naa_shapefile.zip
d <- st_read(file.path(datadir, "EPA/air_quality/lead_1978std_naa_shapefile"))
tracts <- st_transform(tracts , st_crs(d))
pb1978 = st_intersection(d, tracts) %>%
  mutate(pb1978 = 1) %>% 
  select(GEOID, pb1978)

#remove geometry 
list_epa <- as.list(pb2008, so2, ozone2008, ozone2015, pm1997, pm2006, pm2012 , pb1978, so21971 , no2, co, pm10, tracts)
lapply(list_epa, st_drop_geometry)

# merge all of the dataframes together
all <- Reduce(function(x,y) merge(x = x, y = y, by = "GEOID", na.omit = FALSE, all = T), 
              list(list_epa))

# replace NAs with zeros
all[is.na(all)] <- 0
fwrite(all, file = file.path(cleandir, "air_quality_tracts.csv"))



